name: Deploy Awaaz to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy awaaz folder to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./JavaScript-Projects/awaaz
